# Generated by Django 2.0.13 on 2022-03-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yzarticles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'units',
            },
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Book',
        ),
        migrations.AddField(
            model_name='entry',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzarticles.Book'),
        ),
    ]
